# Generated by Django 2.1.2 on 2018-10-16 12:06

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.PositiveIntegerField(help_text="The show's ID on the TMDB API.", primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="The show's name on the TMDB API.", max_length=100, null=True)),
                ('description', models.TextField(help_text="The show's overview on the TMDB API.", null=True)),
            ],
        ),
    ]
