# Generated by Django 2.1.2 on 2018-10-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='APIShow',
        ),
    ]
