# Generated by Django 2.1.2 on 2018-10-16 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('series', '0002_auto_20181016_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='apishow',
            name='followers',
            field=models.ManyToManyField(blank=True, help_text='Users that will receive alerts about this show.', related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
