# Generated by Django 2.1.2 on 2018-10-16 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_apishow_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='apishow',
            name='first_followed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the show was first followed.'),
            preserve_default=False,
        ),
    ]
