# Generated by Django 2.1.2 on 2018-10-26 09:37

from django.db import migrations

from tmdb.shortcuts import retrieve_show


def populate_logo_path(apps, schema_editor):
    APIShow = apps.get_model('series.APIShow')
    for show in APIShow.objects.all():
        print('Retrieving show', show.id)
        loaded_show = retrieve_show(show.id)
        show.small_logo_path = loaded_show.small_logo_path
        show.save()


def undo(apps, schema_editor):
    # Nothing special to do when rolling back
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('series', '0005_apishow_small_logo_path'),
    ]

    operations = [
        migrations.RunPython(populate_logo_path, undo),
    ]
